version: "3.9"
services:
  dev:
    build: .
    hostname: vscode.docker.internal
    # r00t
    user: 0:0
    ports:
      - 0.0.0.0:4443:443/tcp
    volumes:
      - .local/share/code-server/User/settings.json:/root/.local/share/code-server/User/settings.json:rw
      - .certificates:/certificates:ro
      - ./favicon.ico:/usr/lib/code-server/src/browser/media/favicon.ico:ro
      - /:/linux:rw

